var ORDER_STATUS;
(function (ORDER_STATUS) {
    ORDER_STATUS[ORDER_STATUS["PENDING"] = 0] = "PENDING";
    ORDER_STATUS[ORDER_STATUS["SHIPPED"] = 1] = "SHIPPED";
    ORDER_STATUS[ORDER_STATUS["DELIVERED"] = 2] = "DELIVERED";
    ORDER_STATUS[ORDER_STATUS["RETURNED"] = 3] = "RETURNED";
})(ORDER_STATUS || (ORDER_STATUS = {}));
var isPending = ORDER_STATUS.PENDING;
console.log(isPending);
